### ISSUE TITLE
fix: `All 704 Icons` download button

### ISSUE THREAD

**Issue by RayyanRNKJ** [astrit/css.gg#79]
### As screen height decreases `button` height decreases.

![Screenshot 2021-11-18 at 22-29-07 Add R - CSS Icons](https://user-images.githubusercontent.com/64679235/142461854-0b14a015-f042-4719-b78d-60ee75ea2515.png)

**Comment by astrit** [comment]
Thanks for reporting this @RayyanRNKJ will take care of it

**Comment by astrit** [comment]
Hi @RayyanRNKJ 

Sorry for late reply this function has been disabled due to low usage, I did track it and it doesn't make any sense to be there any more 

<img width="505" alt="CleanShot 2023-06-23 at 03 33 31@2x" src="https://github.com/astrit/css.gg/assets/2398447/8837aeef-c9b0-4194-9940-082383477f60">
